# Generated by Django 5.2 on 2026-04-06 18:00

import apps.home.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(help_text='JPG, PNG o WEBP. Resolución recomendada: 1920×600px. Mínimo: 1200×375px.', upload_to='banners/', validators=[apps.home.validators.validar_extension_imagen, apps.home.validators.validar_resolucion_banner])),
                ('imagen_alt', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('url_texto', models.CharField(blank=True, max_length=100)),
                ('url_externa', models.BooleanField(default=True)),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden', 'publicado'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Docencia, Investigación)', max_length=150)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de visualización de la categoría')),
                ('publicado', models.BooleanField(default=True, help_text='Indica si la categoría se muestra')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=150)),
                ('sufijo', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.ImageField(upload_to='indicadores/estatico/')),
                ('icono_gif', models.ImageField(blank=True, null=True, upload_to='indicadores/gif/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en el home')),
                ('orden_destacado', models.PositiveIntegerField(blank=True, help_text='Orden en el home', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='home.categoriaindicador')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('destacado', False), ('icono_gif__isnull', False), _connector='OR'), name='gif_required_if_destacado')],
            },
        ),
    ]
