# Generated by Django 5.2 on 2026-04-17 20:45

import apps.home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagen_mobile',
            field=models.ImageField(blank=True, help_text='Mobile: recomendado 720×960px.', null=True, upload_to='banners/mobile/', validators=[apps.home.validators.validar_extension_imagen, apps.home.validators.validar_resolucion_banner_mobile]),
        ),
    ]
